name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the production image
      run: docker build . --file Dockerfile --tag myproject/next_app:$(date +%s) --tag myproject/next_app:latest --target prod_static
    - name: Build the start image
      run: docker build . --file Dockerfile --tag myproject/next_app:local --target start
